workspace = "/data/disk1/delta"
trigger = "t1"
jump_run = [112]

[paths]
raw_xia0 = "/data/disk3/delta/raw/xia0"
raw_xia1 = "/data/disk3/delta/raw/xia1"
raw_xia2 = "/data/disk3/delta/raw/xia2"
raw_vme = "/data/disk1/delta/ore/vme"
ore = "ore"
grit = "grit"
grain = "grain"
ingot = "ingot"

[prefix]
raw_xia0 = "data"
raw_xia1 = "data"
raw_xia2 = "data"
raw_vme = "data"
